import ast
import re
import sys
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parent
RUNTIME_INPUT = ROOT / "requirements.in"
DEV_INPUT = ROOT / "requirements-dev.in"
RUNTIME_LOCK = ROOT / "requirements.txt"
DEV_LOCK = ROOT / "requirements-dev.txt"

IMPORT_TO_PACKAGE = {
    "dotenv": "python-dotenv",
    "flask": "flask",
    "httpx": "httpx",
    "matplotlib": "matplotlib",
    "requests": "requests",
    "serpapi": "google-search-results",
    "yaml": "pyyaml",
}
EXPECTED_RUNTIME_PACKAGES = set(IMPORT_TO_PACKAGE.values())
EXPECTED_DEV_INPUT = {"pip-tools", "pytest", "ruff"}
EXCLUDED_PARTS = {
    ".git",
    ".pytest_cache",
    "__pycache__",
    "data",
    "tests",
}


def _input_requirements(path: Path) -> set[str]:
    requirements = set()
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith(("#", "-")):
            continue
        name = re.split(r"[<=>!~\[]", line, maxsplit=1)[0]
        requirements.add(name.lower().replace("_", "-"))
    return requirements


def _production_external_imports() -> set[str]:
    python_files = [
        path
        for path in ROOT.rglob("*.py")
        if not any(part in EXCLUDED_PARTS for part in path.relative_to(ROOT).parts)
        and not path.name.startswith("test_")
    ]
    local_modules = {path.stem for path in python_files}
    local_modules.update(
        path.name
        for path in ROOT.iterdir()
        if path.is_dir() and not path.name.startswith(".")
    )
    imported = set()
    for path in python_files:
        tree = ast.parse(path.read_text(encoding="utf-8-sig"), filename=str(path))
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imported.update(alias.name.split(".", 1)[0] for alias in node.names)
            elif (
                isinstance(node, ast.ImportFrom)
                and node.level == 0
                and node.module
            ):
                imported.add(node.module.split(".", 1)[0])
    return {
        module
        for module in imported
        if module not in sys.stdlib_module_names and module not in local_modules
    }


def _assert_hashed_pip_compile_lock(testcase, path: Path, expected: set[str]):
    text = path.read_text(encoding="utf-8")
    testcase.assertIn("This file is autogenerated by pip-compile", text)
    testcase.assertIn("--allow-unsafe", text)
    testcase.assertIn("--strip-extras", text)
    testcase.assertNotIn("not pinned", text)
    testcase.assertIn("--hash=sha256:", text)
    testcase.assertNotIn("--index-url", text)
    testcase.assertNotIn("--trusted-host", text)
    testcase.assertNotRegex(text, r"(?im)^\s*[^#\s].*@\s*file:")
    testcase.assertNotRegex(text, r"(?i)\b(?:pywin32|win32api|conda)\b")

    pinned = {
        match.group(1).lower().replace("_", "-")
        for match in re.finditer(r"(?m)^([a-zA-Z0-9_.-]+)==[^\s\\]+", text)
    }
    testcase.assertTrue(expected <= pinned, f"{path.name} 缺少锁定包: {expected - pinned}")


class DependencyLockingTest(unittest.TestCase):
    def test_runtime_input_exactly_matches_production_direct_imports(self):
        external_imports = _production_external_imports()
        self.assertEqual(external_imports, set(IMPORT_TO_PACKAGE))
        self.assertEqual(_input_requirements(RUNTIME_INPUT), EXPECTED_RUNTIME_PACKAGES)

    def test_dev_input_declares_only_test_and_lock_tooling(self):
        text = DEV_INPUT.read_text(encoding="utf-8")
        self.assertIn("-c requirements.txt", text)
        self.assertEqual(_input_requirements(DEV_INPUT), EXPECTED_DEV_INPUT)

    def test_runtime_and_dev_locks_are_hashed_pip_compile_outputs(self):
        _assert_hashed_pip_compile_lock(
            self,
            RUNTIME_LOCK,
            EXPECTED_RUNTIME_PACKAGES,
        )
        _assert_hashed_pip_compile_lock(
            self,
            DEV_LOCK,
            EXPECTED_DEV_INPUT | {"pip", "setuptools"},
        )


if __name__ == "__main__":
    unittest.main()
